import Lean4LPD.Pauli.LayerLadder
import Lean4LPD.Pauli.DiscardWitness
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds

/-!
# Non-vacuity tests for the physical multi-jump ladder

These tests instantiate `pauliMultiLadder` and `layerN_le_majorant` from
`Lean4LPD.Pauli.LayerLadder`, the recurrence behind `apd:eq:composition_majorant` in
`apd:rmk:multijump`, on data whose high-weight sector is nonempty and actually receives mass.

Here `n = 2`, `k_o = 1` and `k_h = 2`. Every layer is the single rotation generated by `XX`
through the nonzero angle `1/100`. The retained sets keep all coefficients after the first layer
of each two-layer block and cut above weight one after the second. The expansion parameter
`betaOf` is proved to be below one for this data; it is not supplied as a hypothesis.

## Main results

* `physical`: the `MultiLadder` obtained from `pauliMultiLadder` on this data.
* `physical_N_one_pos`: its mass above rung one is strictly positive after the first layer.
* `boundary_highNorm_zero`: after the cut at the second layer the retained high-weight mass is
  zero.
* `entry_positive`: the entry factor into rung one is strictly positive.
-/

namespace Lean4LPD.LayerLadderRegression

open Finset PauliString DiscardWitness

/-- The nonzero small conjugation angle `1/100` used to test the recurrence of
`apd:rmk:multijump`. -/
noncomputable def smallAngle : ℝ := 1 / 100

/-- Every layer is the single rotation generated by the Hermitian two-local Pauli `XX` through
`smallAngle` (`apd:thm:layer_inflow`). -/
noncomputable def layers (_ : ℕ) : List (PauliString 2 × ℝ) := [(G, smallAngle)]

/-- Retained sets for blocks of two layers: keep every coefficient after the first layer of a
block and cut above weight one after the second. This is the end-of-step truncation convention
used with `apd:rmk:multijump`. -/
def keep (T : ℕ) : Finset (PauliIndex 2) :=
  if T % 2 = 0 then univ else (highSet 2 1)ᶜ

/-- The test layers satisfy `IsLayer 2`: pairwise disjoint supports and generators of weight at
most two (`apd:thm:layer_inflow`). -/
theorem layers_isLayer (T : ℕ) : IsLayer 2 ((layers T).map Prod.fst) := by
  constructor
  · simp [layers]
  · intro H hH
    have hH' : H = G := by simpa [layers] using hH
    subst H
    exact weight_G.le

/-- Every generator of the test layers is Hermitian (`apd:thm:layer_inflow`). -/
theorem layers_hermitian (T : ℕ) : ∀ g ∈ layers T, IsSelfAdjoint g.1 := by
  intro g hg
  have hg' : g = (G, smallAngle) := by simpa [layers] using hg
  subst g
  exact isSelfAdjoint_G

/-- The chosen angle bounds the absolute value of its sine, `|sin θ| ≤ smallAngle`. The
hypothesis of `apd:thm:layer_inflow` is on `|sin θ|`, so no sign condition on the angle is
involved. -/
theorem layers_sine_bound (T : ℕ) : ∀ g ∈ layers T, |Real.sin g.2| ≤ smallAngle := by
  intro g hg
  have hg' : g = (G, smallAngle) := by simpa [layers] using hg
  subst g
  simpa [smallAngle] using (Real.abs_sin_le_abs (x := smallAngle))

/-- The expansion parameter `β = 2e·w₂·a = e/25` of the test data is below one, by `e < 3`.
This places the data in the regime of `apd:rmk:multijump` where the entry-factor series
converges. -/
theorem beta_small : betaOf 1 1 smallAngle < 1 := by
  unfold betaOf rungW smallAngle
  norm_num
  nlinarith [Real.exp_one_lt_three]

/-- The sine of the test angle is strictly positive, so the inflow created below is nonzero
(`apd:rmk:multijump`). -/
theorem sin_small_pos : 0 < Real.sin smallAngle := by
  apply Real.sin_pos_of_pos_of_lt_pi
  · norm_num [smallAngle]
  · have hp := Real.two_le_pi
    norm_num [smallAngle]
    linarith

/-- `pauliMultiLadder` instantiated on the test data. The instance is nondegenerate:
`k_o = 1 < n = 2`, every layer is nonempty, and every angle is nonzero
(`apd:eq:composition_majorant`). -/
noncomputable def physical :=
  pauliMultiLadder layers keep (toMatrix P) (ko := 1) (kh := 2) (by decide)
    layers_isLayer layers_hermitian (by norm_num [smallAngle]) layers_sine_bound
    (by simpa using beta_small) input_local

/-- The first layer maps `P` to `cos θ · P + sin θ · Q`: the sine partner `Q = YX` appears with
amplitude `sin θ`, where `θ = smallAngle` (`apd:rmk:multijump`). -/
theorem first_layer_operator :
    layerTraj layers keep (toMatrix P) 1 =
      (Real.cos smallAngle : ℂ) • toMatrix P + (Real.sin smallAngle : ℂ) • toMatrix Q := by
  rw [layerTraj_succ, layerTraj_zero]
  change truncOp univ (rot (toMatrix G) smallAngle * toMatrix P *
      rot (toMatrix G) (-smallAngle)) = _
  rw [truncOp_univ,
    pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_G sympForm_G_P,
    phaseMul_G_P]

/-- Pauli coefficients are linear on a two-term combination. Helper for
`first_layer_Q_coeff`. -/
theorem coeff_two_terms {n : ℕ} (A B : Matrix (Bits n) (Bits n) ℂ)
    (a b : ℂ) (p : PauliIndex n) :
    coeff (a • A + b • B) p = a * coeff A p + b * coeff B p := by
  simp only [coeff, Matrix.mul_add, Matrix.mul_smul, Matrix.trace_add, Matrix.trace_smul,
    smul_eq_mul]
  ring

/-- The coefficient of the weight-two Pauli `Q` in the retained trajectory after one layer is
`sin smallAngle`, which is nonzero. This is a statement about the coefficient itself, not about
membership of `Q` in a set of reachable Paulis (`apd:rmk:multijump`). -/
theorem first_layer_Q_coeff :
    coeff (layerTraj layers keep (toMatrix P) 1) (cls Q) = (Real.sin smallAngle : ℂ) := by
  have hPQ : coeff (toMatrix P) (cls Q) = 0 := by
    rw [← herm_P, coeff_toMatrix_herm]
    exact ite_eq_right (by decide)
  have hQQ : coeff (toMatrix Q) (cls Q) = 1 := by
    rw [← herm_Q, coeff_toMatrix_herm]
    simp
  rw [first_layer_operator, coeff_two_terms, hPQ, hQQ, mul_zero, mul_one, zero_add]

/-- **Nondegenerate instance:** the mass above rung one is strictly positive after the first
small-angle layer, with `k_o = 1 < n = 2` (`apd:rmk:multijump`). -/
theorem first_layer_highNorm_pos :
    0 < highNorm 1 (layerTraj layers keep (toMatrix P) 1) := by
  by_contra h
  have hn : highNorm 1 (layerTraj layers keep (toMatrix P) 1) = 0 :=
    le_antisymm (le_of_not_gt h) (highNorm_nonneg _ _)
  have hz : restr (highSet 2 1) (coeffVec (layerTraj layers keep (toMatrix P) 1)) = 0 :=
    norm_eq_zero.1 hn
  have hcoord := congrArg (fun x : EuclideanSpace ℂ (PauliIndex 2) => x.ofLp (cls Q)) hz
  have hQ : cls Q ∈ highSet 2 1 := mem_highSet.2 (by simp [weight_Q])
  simp only [restr_apply, ite_eq_left hQ, coeffVec_apply, WithLp.ofLp_zero,
    Pi.zero_apply, first_layer_Q_coeff, Complex.ofReal_eq_zero] at hcoord
  exact (ne_of_gt sin_small_pos) hcoord

/-- The field `N` of the constructed `MultiLadder` is strictly positive at rung one after one
layer, so the high-weight sector of the ladder itself is occupied
(`apd:eq:composition_majorant`). -/
theorem physical_N_one_pos : 0 < physical.N 1 1 := by
  simpa [physical, pauliMultiLadder, layerN, rungWeight] using first_layer_highNorm_pos

/-- The same trajectory is cut at the second layer, after which its retained high-weight mass
is zero. This post-cut value is distinct from the pre-cut mass of the discarded component
(`apd:rmk:multijump`). -/
theorem boundary_highNorm_zero : highNorm 1 (layerTraj layers keep (toMatrix P) 2) = 0 := by
  rw [layerTraj_succ]
  change highNorm 1 (truncOp (highSet 2 1)ᶜ _) = 0
  exact highNorm_truncOp_compl 1 _

example : 0 < physical.N 1 1 ∧ physical.N 1 2 = 0 := by
  refine ⟨physical_N_one_pos, ?_⟩
  simpa [physical, pauliMultiLadder, layerN, rungWeight] using boundary_highNorm_zero

example (m T : ℕ) (hm : 1 ≤ m) : physical.N m (T + 1) ≤ physical.N m T +
    (∑ j ∈ Ico 1 m, epsJump 1 1 smallAngle j m * physical.N (m - j) T) +
      entryFactor 1 1 smallAngle m * pauliNorm (toMatrix P) := by
  simpa using physical.step m T hm

example (m : ℕ) (hm : 1 ≤ m) : Summable (fun i => epsJump 1 1 smallAngle (m + i) m) :=
  summable_epsJump_tail (by norm_num) (by norm_num) (by norm_num [smallAngle]) hm beta_small

/-- The entry factor into rung one is strictly positive on the test data, so the recurrence of
`apd:eq:composition_majorant` is tested with a nonzero, convergent entry term. -/
theorem entry_positive : 0 < entryFactor 1 1 smallAngle 1 := by
  have h := sum_Ico_epsJump_le_entryFactor (kh1 := 1) (c := 1) (a := smallAngle)
    (by norm_num) (by norm_num) (by norm_num [smallAngle]) (m := 1) (by decide) beta_small 2
  have hlead : 0 < epsJump 1 1 smallAngle 1 1 := by norm_num [epsJump, rungW, smallAngle]
  exact hlead.trans_le (by simpa using h)

example (m T : ℕ) (hm : 1 ≤ m) : layerN layers keep (toMatrix P) 1 2 m T ≤
    MultiLadder.majorant (epsJump 1 1 smallAngle) (entryFactor 1 1 smallAngle)
      (pauliNorm (toMatrix P)) m T := by
  simpa using layerN_le_majorant layers keep (toMatrix P) (ko := 1) (kh := 2)
    (by decide) layers_isLayer layers_hermitian (by norm_num [smallAngle]) layers_sine_bound
    (by simpa using beta_small) input_local T m hm

example {ko kh : ℕ} (hkh : 2 ≤ kh) :
    (rungWeight ko kh 1 : ℝ) = rungW (kh - 1 : ℕ) ((ko : ℝ) / (kh - 1 : ℕ)) 1 :=
  rungWeight_cast_eq_rungW hkh (by decide)

#print axioms summable_epsJump_tail
#print axioms sum_Ico_epsJump_le_entryFactor
#print axioms highNorm_layerConj_le_multi
#print axioms layerN_step
#print axioms pauliMultiLadder
#print axioms layerN_le_majorant
#print axioms physical
#print axioms physical_N_one_pos
#print axioms boundary_highNorm_zero
#print axioms entry_positive

end Lean4LPD.LayerLadderRegression
