import Lean4LPD.Pauli.LayerFlow

/-!
# Tests for the layer inflow expansion

Boundary cases and a nondegenerate example for the decomposition of a disjoint-support layer
into its exactly-`j`-jump components, as developed in `Lean4LPD.Pauli.LayerFlow`
(`apd:thm:layer_inflow`, `apd:rmk:multijump`).

* Boundary cases: the empty layer, a one-rotation layer, and a system of zero qubits.
* `triple_jump_magnitude`: for a layer of three disjointly supported two-local generators, the
  three-jump matrix entry from a weight-three Pauli to a weight-six Pauli has modulus
  `|sin θ|³`. The coefficient itself is computed, so the example is nondegenerate.
* `negative_angle_triple_inflow`: at `θ = -π/2` this entry of the inflow block across the cutoff
  `w* = 5` has modulus one, which is why the inflow bound is parametrised by `|sin θ|`.
* The last example shows that pairwise commuting generators with overlapping supports can
  anticommute with a Pauli more often than it has occupied sites (`apd:rmk:disjoint`).
-/

open Lean4LPD Lean4LPD.PauliString Finset Matrix
open scoped Matrix.Norms.L2Operator

namespace LayerFlowTests

/-- The empty layer has no component with a positive number of jumps
(`apd:thm:layer_inflow`). -/
example {n : ℕ} (j : ℕ) (y : EuclideanSpace ℂ (PauliIndex n)) :
    layerJump [] (j + 1) y = 0 := rfl

/-- A one-rotation layer has no two-jump component (`apd:thm:layer_inflow`). -/
example {n : ℕ} (G : PauliString n) (θ : ℝ) (y : EuclideanSpace ℂ (PauliIndex n)) :
    layerJump [(G, θ)] 2 y = 0 :=
  layerJump_eq_zero_of_length_lt _ _ (by simp) _

/-- The absolute-sine maximum `layerSigma` of the empty layer is zero by definition, so
statements that use it need no nonemptiness side condition (`apd:thm:layer_inflow`). -/
example : layerSigma ([] : List (PauliString 0 × ℝ)) = 0 := rfl

/-- On zero qubits every Pauli has weight zero, so no destination lies above the cutoff and the
inflow block vanishes, even for a nonempty layer of scalar generators
(`apd:thm:layer_inflow`). -/
example (L : List (PauliString 0 × ℝ)) (j : ℕ) : layerInflowMatrix L 0 j = 0 := by
  ext p q
  have hp : wt p = 0 := by simp [wt, weight, support]
  simp [layerInflowMatrix, hp]

/-- `G₁ = X₀X₃`. Together with `G₂ = X₁X₄` and `G₃ = X₂X₅` it forms a layer of three disjointly
supported two-local generators, the multi-jump setting of `apd:rmk:multijump`. -/
def G₁ : PauliString 6 := ⟨![1, 0, 0, 1, 0, 0], 0, 0⟩
/-- `G₂ = X₁X₄`. -/
def G₂ : PauliString 6 := ⟨![0, 1, 0, 0, 1, 0], 0, 0⟩
/-- `G₃ = X₂X₅`. -/
def G₃ : PauliString 6 := ⟨![0, 0, 1, 0, 0, 1], 0, 0⟩
/-- The weight-three source index `Z₀Z₁Z₂`. -/
def q : PauliIndex 6 := (0, ![1, 1, 1, 0, 0, 0])
/-- The weight-six destination index, obtained from `q` by taking the sine partner under each
of the three generators in turn. -/
def p : PauliIndex 6 := partner G₁ (partner G₂ (partner G₃ q))
/-- The layer of the three rotations generated by `G₁`, `G₂`, `G₃`, all through the angle `θ`. -/
def triple (θ : ℝ) : List (PauliString 6 × ℝ) := [(G₁, θ), (G₂, θ), (G₃, θ)]

/-- The three generators satisfy `IsLayer 2`: they are two-local with pairwise disjoint
supports, which is stronger than pairwise commutation (`apd:rmk:multijump`). -/
theorem triple_isLayer (θ : ℝ) : IsLayer 2 ((triple θ).map Prod.fst) := by
  constructor
  · change [G₁, G₂, G₃].Pairwise _
    decide
  · intro G hG
    change G ∈ [G₁, G₂, G₃] at hG
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hG
    rcases hG with rfl | rfl | rfl <;> decide

/-- The index `q` has weight three and the index `p` has weight six, so they lie on either side
of the cutoff `w* = 5` (`apd:rmk:multijump`). -/
theorem triple_weights : wt q = 3 ∧ wt p = 6 := by decide

/-- All three generators are Hermitian, so by `coeffVec_layerConj` the coefficient action
`layerAct` of the layer is that of genuine matrix conjugation (`apd:rmk:multijump`). -/
theorem triple_hermitian (θ : ℝ) : ∀ g ∈ triple θ, IsSelfAdjoint g.1 := by
  intro g hg
  simp only [triple, List.mem_cons, List.not_mem_nil, or_false] at hg
  rcases hg with rfl | rfl | rfl <;> dsimp only <;> rw [isSelfAdjoint_iff_phase] <;> decide

/-- **The three-jump matrix entry from `q` to `p` has modulus `|sin θ|³`.** This is a statement
about the coefficient itself, not about membership of `p` in an angle-independent set of
reachable Paulis (`apd:rmk:multijump`). -/
theorem triple_jump_magnitude (θ : ℝ) :
    ‖layerJumpMatrix (triple θ) 3 p q‖ = |Real.sin θ| ^ 3 := by
  have h₁ : sympForm G₁ (herm p) ≠ 0 := by decide
  have h₂ : sympForm G₂ (herm (partner G₁ p)) ≠ 0 := by decide
  have h₃ : sympForm G₃ (herm (partner G₂ (partner G₁ p))) ≠ 0 := by decide
  have hq : partner G₃ (partner G₂ (partner G₁ p)) = q := by decide
  simp only [layerJumpMatrix, triple, layerJump, stayAct_zero, jumpAct_zero, zero_add,
    add_zero, jumpAct_apply, h₁, h₂, h₃, ↓reduceIte, hq,
    Pi.single_eq_same, norm_mul, norm_neg, partnerSign, norm_iPow, one_mul, mul_one,
    Complex.norm_real, Real.norm_eq_abs]
  ring

/-- At the negative conjugation angle `θ = -π/2` the three-jump entry of the inflow block across
`w* = 5` has modulus one. A bound stated with the signed `sin θ` in place of `|sin θ|` would fail
here, since `sin³ θ = -1`; this is why the formal `apd:thm:layer_inflow` is parametrised by a
bound on `|sin θ|`. The entry is also a multi-jump inflow in the sense of `apd:rmk:multijump`:
mass enters the sector above `w* = 5` directly from weight three. -/
theorem negative_angle_triple_inflow :
    ‖layerInflowMatrix (triple (-(Real.pi / 2))) 5 3 p q‖ = 1 := by
  have hwtp : 5 < wt p := by rw [triple_weights.2]; decide
  have hwtq : wt q ≤ 5 := by rw [triple_weights.1]; decide
  rw [layerInflowMatrix, ite_eq_left ⟨hwtp, hwtq⟩, triple_jump_magnitude,
    Real.sin_neg, Real.sin_pi_div_two]
  norm_num

/-- On the example input, matrix conjugation by the layer is the sum of its exactly-`j`-jump
components for `j = 0, …, 3` (`apd:rmk:multijump`). -/
example (θ : ℝ) :
    coeffVec (layerConj (triple θ) (toMatrix (herm q)))
      = ∑ j ∈ range 4, layerJump (triple θ) j (coeffVec (toMatrix (herm q))) := by
  rw [coeffVec_layerConj _ (triple_hermitian θ), layerAct_eq_sum_layerJump]
  rfl

/-- Pairwise commuting generators with overlapping supports can anticommute with a Pauli more
often than it has occupied sites: here `X₀X₁` and `X₀X₂` commute and both anticommute with the
weight-one Pauli `Z₀`. This is why `apd:thm:layer_inflow` assumes disjoint supports and not
just commutation (`apd:rmk:disjoint`). -/
example :
    let A : PauliString 3 := ⟨![1, 1, 0], 0, 0⟩
    let B : PauliString 3 := ⟨![1, 0, 1], 0, 0⟩
    let z : PauliIndex 3 := (0, ![1, 0, 0])
    sympForm A B = 0 ∧ layerAntiCount [A, B] z = 2 ∧ wt z = 1 := by decide

#print axioms coeffVec_layerConj
#print axioms layerAct_eq_sum_layerJump
#print axioms row_sum_norm_layerJumpMatrix_le
#print axioms col_sum_norm_layerJumpMatrix_le
#print axioms norm_layerInflowMatrix_le
#print axioms norm_layerInflowMatrix_le_factorial
#print axioms layerInflowMatrix_mulVec
#print axioms norm_restr_layerAct_le_sum_inflow
#print axioms norm_layerInflowMatrix_clm_le_restr
#print axioms negative_angle_triple_inflow

end LayerFlowTests
