import Lean4LPD.Pauli.LayerError
import Lean4LPD.Pauli.DiscardWitness
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds

/-!
# Non-vacuity tests for the layer-level truncation error

These tests instantiate the results of `Lean4LPD.Pauli.LayerError` (the discarded operator of
`apd:eq:step_component`, the norm-level telescope of `apd:thm:triangle`, and the summed bound
`apd:eq:total_high_weight_norm`) at concrete points where truncation removes a nonzero
operator. Every hypothesis of the instantiated theorems (layer structure, Hermiticity, the
absolute-sine bound, convergence of the entry factor, input locality) is proved for the test
data; none is assumed.

## Two-qubit tests (`Lean4LPD.LayerErrorRegression`)

Here `n = 2`, the input is `P = ZI` (`k_o = 1`), every layer is the single rotation generated by
`G = XX` (`k_h = 2`) through the nonzero angle `a = 1/100`, and the cutoff is `w* = 1`.

* `one_layer_discard_pos`, `two_layer_discard_pos`: the first discarded operator is nonzero for
  blocks of one layer and of two layers.
* `retained_mass_replacement_false`: the high-weight mass of the retained operator, which
  vanishes after every cut, does not bound the discarded norm.
* `actual_sum_bound`, `actual_operator_bound`, `actual_cZero_bound`: the shifted-chain bound and
  its `c₀` form hold on this data with all hypotheses discharged.
* `zero_layers_boundary_counterexample`: the hypothesis `0 < Γ` of
  `layerScheduledTraj_at_boundary` cannot be dropped.

## Three-qubit tests (`Lean4LPD.LayerErrorThreeQubitRegression`)

Here `n = 3`, the input is `ZII`, the layers alternate between the rotations generated by `XXI`
and `-IZX` with angle `1/1000`, a step is a block of `Γ = 2` layers, `m* = 1`, and the cutoff is
`w* = 2`.

* `afterTwo_expansion`, `coeff_afterTwo_R`: one block creates the weight-three Pauli `YYX` with
  coefficient `-sin² θ`.
* `first_discard_pos`, `model_discard_sum_pos`: the discarded norms are strictly positive.
* `model_bound_instance`: `pauliNorm_layerStep_error_le_model_of_source_regime` applies at
  `r = 20`, `α = 1`, `t = 1/50`; `inside_model_threshold` shows that `t < tZeroModel` there.
-/

namespace Lean4LPD.LayerErrorRegression

open Finset PauliString DiscardWitness

/-- The nonzero small angle `1/100` used by every rotation of the two-qubit tests of
`apd:eq:total_high_weight_norm`. -/
noncomputable def a : ℝ := 1 / 100

/-- Every layer is the single rotation generated by `XX` through the nonzero angle `a`; no
layer is padded with a zero angle (`apd:thm:layer_inflow`). -/
noncomputable def layers (_ : ℕ) : List (PauliString 2 × ℝ) := [(G, a)]

/-- The test layers satisfy `IsLayer 2`: pairwise disjoint supports and generators of weight at
most two (`apd:thm:layer_inflow`). -/
theorem layers_isLayer (T : ℕ) : IsLayer 2 ((layers T).map Prod.fst) := by
  constructor
  · simp [layers]
  · intro H hH
    have hH' : H = G := by simpa [layers] using hH
    subst H
    exact weight_G.le

/-- Every generator of the test layers is Hermitian (`apd:thm:layer_inflow`). -/
theorem layers_hermitian (T : ℕ) : ∀ g ∈ layers T, IsSelfAdjoint g.1 := by
  intro g hg
  have hg' : g = (G, a) := by simpa [layers] using hg
  subst g
  exact isSelfAdjoint_G

/-- The absolute-sine hypothesis `|sin θ| ≤ a` holds at the chosen angle
(`apd:thm:layer_inflow`). -/
theorem layers_sine_bound (T : ℕ) : ∀ g ∈ layers T, |Real.sin g.2| ≤ a := by
  intro g hg
  have hg' : g = (G, a) := by simpa [layers] using hg
  subst g
  simpa [a] using (Real.abs_sin_le_abs (x := a))

/-- The expansion parameter `β = 2e·w₂·a` of the test data is below one, so the entry-factor
series converges. The hypothesis `hb` of the instantiated theorems is thereby proved rather than
assumed (`apd:rmk:multijump`). -/
theorem beta_small : betaOf 1 1 a < 1 := by
  unfold betaOf rungW a
  norm_num
  nlinarith [Real.exp_one_lt_three]

/-- The same data lie in the regime `β ≤ 1/2` required by the `c₀` form of the bound
(`apd:eq:entry_bound`). -/
theorem beta_half : betaOf 1 1 a ≤ 1 / 2 := by
  unfold betaOf rungW a
  norm_num
  nlinarith [Real.exp_one_lt_three]

/-- `sin a` and `sin (2a)` are strictly positive. These are the amplitudes created by a block
of `Γ = 1` and of `Γ = 2` layers (`apd:eq:step_component`). -/
theorem sin_a_pos : 0 < Real.sin a ∧ 0 < Real.sin (2 * a) := by
  constructor <;> apply Real.sin_pos_of_pos_of_lt_pi
  · norm_num [a]
  · have h := Real.two_le_pi; norm_num [a]; linarith
  · norm_num [a]
  · have h := Real.two_le_pi; norm_num [a]; linarith

/-- A one-layer block maps `P` to `cos a · P + sin a · Q`, creating the sine partner `Q = YX`
(`apd:eq:step_component`). -/
theorem block_one : layerBlockTraj layers (toMatrix P) 1 =
    (Real.cos a : ℂ) • toMatrix P + (Real.sin a : ℂ) • toMatrix Q := by
  change rot (toMatrix G) a * toMatrix P * rot (toMatrix G) (-a) = _
  rw [pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_G sympForm_G_P, phaseMul_G_P]

/-- A two-layer block, both of whose rotations have the nonzero angle `a`, acts on `P` as the
rotation through `2a` (`apd:eq:step_component`). -/
theorem block_two : layerBlockTraj layers (toMatrix P) 2 =
    (Real.cos (2 * a) : ℂ) • toMatrix P + (Real.sin (2 * a) : ℂ) • toMatrix Q := by
  have hG := toMatrix_mul_self_of_isSelfAdjoint isSelfAdjoint_G
  change rot (toMatrix G) a * (rot (toMatrix G) a * toMatrix P * rot (toMatrix G) (-a)) *
      rot (toMatrix G) (-a) = _
  calc
    _ = (rot (toMatrix G) a * rot (toMatrix G) a) * toMatrix P *
        (rot (toMatrix G) (-a) * rot (toMatrix G) (-a)) := by simp only [mul_assoc]
    _ = rot (toMatrix G) (2 * a) * toMatrix P * rot (toMatrix G) (-(2 * a)) := by
      rw [rot_mul_rot hG, rot_mul_rot hG,
        show a + a = 2 * a by ring, show -a + -a = -(2 * a) by ring]
    _ = _ := by
      rw [pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_G sympForm_G_P, phaseMul_G_P]

/-- The coefficient of the weight-two Pauli `Q` in `cos t · P + sin t · Q` is `sin t`. This is
the amplitude of the discarded operator of `apd:eq:step_component` in the tests below. -/
theorem coeff_cos_sin_Q (t : ℝ) :
    coeff ((Real.cos t : ℂ) • toMatrix P + (Real.sin t : ℂ) • toMatrix Q) (cls Q) =
      (Real.sin t : ℂ) := by
  have hPQ : coeff (toMatrix P) (cls Q) = 0 := by
    rw [← herm_P, coeff_toMatrix_herm]
    exact ite_eq_right (by decide)
  have hQQ : coeff (toMatrix Q) (cls Q) = 1 := by
    rw [← herm_Q, coeff_toMatrix_herm]
    simp
  have hlin : ∀ (A B : Matrix (Bits 2) (Bits 2) ℂ) (c s : ℂ),
      coeff (c • A + s • B) (cls Q) = c * coeff A (cls Q) + s * coeff B (cls Q) := by
    intro A B c s
    simp only [coeff, Matrix.mul_add, Matrix.mul_smul, Matrix.trace_add, Matrix.trace_smul,
      smul_eq_mul]
    ring
  rw [hlin, hPQ, hQQ, mul_zero, mul_one, zero_add]

/-- A positive coefficient on `Q = YX` forces strictly positive high-weight norm above weight
one. The argument uses the coefficient itself, not membership of `Q` in a set of reachable
Paulis (`apd:eq:step_component`). -/
theorem highNorm_pos_of_Q_coeff (A : Matrix (Bits 2) (Bits 2) ℂ) (s : ℝ) (hs : 0 < s)
    (hcoeff : coeff A (cls Q) = (s : ℂ)) : 0 < highNorm 1 A := by
  by_contra h
  have hn : highNorm 1 A = 0 := le_antisymm (le_of_not_gt h) (highNorm_nonneg _ _)
  have hz : restr (highSet 2 1) (coeffVec A) = 0 := norm_eq_zero.1 hn
  have he := congrArg (fun x : EuclideanSpace ℂ (PauliIndex 2) => x.ofLp (cls Q)) hz
  have hQ : cls Q ∈ highSet 2 1 := mem_highSet.2 (by simp [weight_Q])
  simp only [restr_apply, ite_eq_left hQ, coeffVec_apply, WithLp.ofLp_zero,
    Pi.zero_apply, hcoeff, Complex.ofReal_eq_zero] at he
  exact (ne_of_gt hs) he

/-- The first discarded operator of the one-layer step has strictly positive norm
(`apd:eq:step_component`). -/
theorem one_layer_discard_pos : 0 < pauliNorm (discardedLayerStep layers 1 1 (toMatrix P) 0) := by
  rw [pauliNorm_discardedLayerStep, layerStepTraj_zero, block_one]
  exact highNorm_pos_of_Q_coeff _ _ sin_a_pos.1 (coeff_cos_sin_Q a)

/-- The first discarded operator of the two-layer step, both of whose angles are nonzero, has
strictly positive norm (`apd:eq:step_component`). -/
theorem two_layer_discard_pos : 0 < pauliNorm (discardedLayerStep layers 2 1 (toMatrix P) 0) := by
  rw [pauliNorm_discardedLayerStep, layerStepTraj_zero, block_two]
  exact highNorm_pos_of_Q_coeff _ _ sin_a_pos.2 (coeff_cos_sin_Q (2 * a))

/-- The high-weight mass of the retained operator at a step boundary cannot replace the
discarded norm in `apd:eq:total_high_weight_norm`: here the former is zero and the latter is
strictly positive. -/
theorem retained_mass_replacement_false :
    ¬ pauliNorm (discardedLayerStep layers 2 1 (toMatrix P) 0) ≤
      highNorm 1 (layerStepTraj layers 2 1 (toMatrix P) 1) := by
  rw [highNorm_layerStepTraj_succ layers 2 1 (toMatrix P) 0]
  exact not_le_of_gt two_layer_discard_pos

/-- The sum of discarded norms obeys the shifted-chain bound
`sum_pauliNorm_discardedLayerStep_le_chain` on the small-angle data, for every block length
`Γ > 0` and every step count `r`, with all hypotheses of that theorem discharged
(`apd:eq:total_high_weight_norm`). -/
theorem actual_sum_bound (Γ : ℕ) (hΓ : 0 < Γ) (r : ℕ) :
    (∑ d ∈ range r, pauliNorm (discardedLayerStep layers Γ 1 (toMatrix P) d)) ≤
      pauliNorm (toMatrix P) * ∑ k ∈ range 1,
        ((((r : ℝ) + 1) * Γ) ^ (k + 1) / (Nat.factorial (k + 1) : ℝ)) *
          chain (epsJump 1 1 a) (entryFactor 1 1 a) (k + 1) 1 := by
  simpa [rungWeight] using sum_pauliNorm_discardedLayerStep_le_chain layers Γ (toMatrix P)
    (ko := 1) (kh := 2) (m := 1) hΓ (by decide) layers_isLayer layers_hermitian
    (by norm_num [a]) layers_sine_bound (by decide) (by simpa using beta_small) input_local r

/-- The one-step operator error itself, the untruncated block minus the retained operator, is
nonzero for the two-layer execution: by `layerStep_telescoping` it equals the first discarded
operator (`apd:thm:triangle`). -/
theorem actual_operator_error_pos :
    0 < pauliNorm (((layerBlockEnd layers 2) ^ 1) (toMatrix P) -
      layerStepTraj layers 2 1 (toMatrix P) 1) := by
  have h := layerStep_telescoping layers 2 1 (toMatrix P) 1
  simp only [Finset.sum_range_one, Nat.sub_self, Nat.zero_sub, pow_zero,
    AddMonoid.End.one_apply] at h
  rw [h]
  exact two_layer_discard_pos

/-- The operator error of the test execution obeys the shifted-chain bound
`pauliNorm_layerStep_error_le_chain` (`apd:thm:triangle`; `apd:eq:total_high_weight_norm`). -/
theorem actual_operator_bound (Γ : ℕ) (hΓ : 0 < Γ) (r : ℕ) :
    pauliNorm (((layerBlockEnd layers Γ) ^ r) (toMatrix P) -
        layerStepTraj layers Γ 1 (toMatrix P) r) ≤
      pauliNorm (toMatrix P) * ∑ k ∈ range 1,
        ((((r : ℝ) + 1) * Γ) ^ (k + 1) / (Nat.factorial (k + 1) : ℝ)) *
          chain (epsJump 1 1 a) (entryFactor 1 1 a) (k + 1) 1 := by
  simpa [rungWeight] using pauliNorm_layerStep_error_le_chain layers Γ (toMatrix P)
    (ko := 1) (kh := 2) (m := 1) hΓ (by decide) layers_isLayer layers_hermitian
    (by norm_num [a]) layers_sine_bound (by decide) (by simpa using beta_small) input_local r

/-- The same nonzero-error execution obeys the `c₀` form of the bound,
`pauliNorm_layerStep_error_le_cZero` (`apd:eq:total_high_weight_norm`/`apd:eq:c0`). The summed
per-step estimate is derived from the evolution and is not a hypothesis. -/
theorem actual_cZero_bound (Γ r : ℕ) (hΓ : 0 < Γ) (hr : 1 ≤ r)
    (A : ℝ) (hA : 0 ≤ A) (haA : a ≤ A / (r : ℝ)) :
    pauliNorm (((layerBlockEnd layers Γ) ^ r) (toMatrix P) -
        layerStepTraj layers Γ 1 (toMatrix P) r) ≤
      (cZero (r : ℝ) 0 (Γ : ℝ) (4 * Real.exp 1 * betaOf 1 1 a) * Γ * A) *
        2 * pauliNorm (toMatrix P) := by
  simpa [rungWeight, rungW, Finset.prod_range_succ] using
    pauliNorm_layerStep_error_le_cZero layers Γ (toMatrix P) (ko := 1) (kh := 2) (m := 0)
      hΓ (by decide) layers_isLayer layers_hermitian (by norm_num [a]) layers_sine_bound
      (by simpa using beta_half) hA hr haA input_local

example (r : ℕ) :
    (∑ d ∈ range r, pauliNorm (discardedLayerStep layers 1 1 (toMatrix P) d)) ≤
      pauliNorm (toMatrix P) * ∑ k ∈ range 1,
        ((((r : ℝ) + 1) * 1) ^ (k + 1) / (Nat.factorial (k + 1) : ℝ)) *
          chain (epsJump 1 1 a) (entryFactor 1 1 a) (k + 1) 1 := by
  simpa using actual_sum_bound 1 (by decide) r

example (r : ℕ) :
    (∑ d ∈ range r, pauliNorm (discardedLayerStep layers 2 1 (toMatrix P) d)) ≤
      pauliNorm (toMatrix P) * ∑ k ∈ range 1,
        ((((r : ℝ) + 1) * 2) ^ (k + 1) / (Nat.factorial (k + 1) : ℝ)) *
          chain (epsJump 1 1 a) (entryFactor 1 1 a) (k + 1) 1 := by
  simpa using actual_sum_bound 2 (by decide) r

example (Γ : ℕ) :
    (∑ d ∈ range 0, pauliNorm (discardedLayerStep layers Γ 1 (toMatrix P) d)) = 0 := by
  simp

/-- A cut at weight zero removes `P = ZI` entirely. Helper for
`zero_layers_boundary_counterexample`. -/
theorem cut_P_at_zero : truncOp (highSet 2 0)ᶜ (toMatrix P) = 0 := by
  rw [truncOp]
  refine Finset.sum_eq_zero fun p hp => ?_
  have hpP : p ≠ cls P := by
    intro h
    subst p
    exact (Finset.mem_compl.1 hp) (mem_highSet.2 (by simp [weight_P]))
  rw [← herm_P, coeff_toMatrix_herm, ite_eq_right hpP, zero_smul]

/-- The hypothesis `0 < Γ` of `layerScheduledTraj_at_boundary` cannot be dropped. At `Γ = 0`
one step of the whole-block recurrence still applies the cut, here removing `P`, whereas the
scheduled trajectory at layer index `1 * 0 = 0` is still the input
(`apd:eq:step_component`). -/
theorem zero_layers_boundary_counterexample :
    layerScheduledTraj layers 0 0 (toMatrix P) (1 * 0) ≠
      layerStepTraj layers 0 0 (toMatrix P) 1 := by
  simp only [mul_zero, layerScheduledTraj_zero, layerStepTraj_succ, layerStepTraj_zero,
    layerBlockTraj_zero, cut_P_at_zero]
  exact toMatrix_ne_zero P

#print axioms layerScheduledTraj_at_boundary
#print axioms layerBlockTraj_eq_scheduled_prefix
#print axioms pauliNorm_discardedLayerStep
#print axioms layerStepMass_reset
#print axioms layerStepMass_inflow
#print axioms sum_pauliNorm_discardedLayerStep_le_chain
#print axioms layerStep_telescoping
#print axioms pauliNorm_layerStep_error_le
#print axioms pauliNorm_layerStep_error_le_chain
#print axioms sum_pauliNorm_discardedLayerStep_le_cZero
#print axioms pauliNorm_layerStep_error_le_cZero
#print axioms pauliNorm_layerStep_error_le_model
#print axioms pauliNorm_layerStep_error_le_model_of_source_regime
#print axioms source_entry_inflation_le_one
#print axioms source_beta_le_half
#print axioms one_layer_discard_pos
#print axioms two_layer_discard_pos
#print axioms actual_operator_error_pos
#print axioms actual_cZero_bound
#print axioms retained_mass_replacement_false
#print axioms zero_layers_boundary_counterexample

end Lean4LPD.LayerErrorRegression

namespace Lean4LPD.LayerErrorThreeQubitRegression

open PauliString

/-- The first two-local generator `XXI` of the three-qubit test of
`apd:thm:one_step_truncation_error`. -/
def G1 : PauliString 3 := ⟨![1, 1, 0], ![0, 0, 0], 0⟩
/-- The second two-local generator `-IZX` of the same test. -/
def G2 : PauliString 3 := ⟨![0, 0, 1], ![0, 1, 0], 2⟩
/-- The weight-one input `ZII`. -/
def P : PauliString 3 := ⟨![0, 0, 0], ![1, 0, 0], 0⟩
/-- The weight-two Pauli `YXI` that the first rotation creates from the input. -/
def Q : PauliString 3 := ⟨![1, 1, 0], ![1, 0, 0], 1⟩
/-- The weight-three Pauli `YYX`, above the cutoff `w* = 2` that corresponds to `m* = 1`. -/
def R : PauliString 3 := ⟨![1, 1, 1], ![1, 1, 0], 2⟩

/-- `G1` is Hermitian, as `apd:thm:layer_inflow` requires of every generator. -/
theorem hG1 : IsSelfAdjoint G1 := isSelfAdjoint_iff_phase.2 (by decide)
/-- `G2` is Hermitian, as `apd:thm:layer_inflow` requires of every generator. -/
theorem hG2 : IsSelfAdjoint G2 := isSelfAdjoint_iff_phase.2 (by decide)
/-- The weights realise `k_o = 1` and `k_h = 2` exactly, and the created Paulis `Q` and `R` have
weights two and three (`apd:thm:one_step_truncation_error`). -/
theorem weights : weight G1 = 2 ∧ weight G2 = 2 ∧ weight P = 1 ∧ weight Q = 2 ∧ weight R = 3 := by
  decide
/-- The sine partner of `P` under the rotation generated by `G1` is `Q`
(`apd:eq:pauli_rotation_branch`). -/
theorem partner_one : phaseMul 1 (G1 * P) = Q := by decide
/-- The sine partner of `Q` under the rotation generated by `G2` is `R`
(`apd:eq:pauli_rotation_branch`). -/
theorem partner_two : phaseMul 1 (G2 * Q) = R := by decide
/-- `P` is the canonical Hermitian representative of its class. -/
theorem herm_P : herm (cls P) = P := by decide
/-- `Q` is the canonical Hermitian representative of its class. -/
theorem herm_Q : herm (cls Q) = Q := by decide
/-- `R = +YYX` is minus the canonical Hermitian representative `herm (cls R)` of its class, so
its coefficient in the Pauli basis is negative (`apd:eq:pauli_rotation_branch`). -/
theorem R_phase : R = phaseMul 2 (herm (cls R)) := by decide

/-- The input conjugated by the two rotations of the first block, written out directly as a
matrix product (`apd:eq:step_component`). -/
noncomputable def afterTwo (θ : ℝ) : Matrix (Bits 3) (Bits 3) ℂ :=
  rot (toMatrix G2) θ * (rot (toMatrix G1) θ * toMatrix P * rot (toMatrix G1) (-θ)) *
    rot (toMatrix G2) (-θ)

/-- Exact expansion of the two-layer block. The `sin² θ` term is the amplitude for climbing two
rungs within one block, one jump in each layer (`apd:rmk:multijump`). -/
theorem afterTwo_expansion (θ : ℝ) :
    afterTwo θ = (Real.cos θ : ℂ) • toMatrix P +
      ((Real.sin θ : ℂ) * (Real.cos θ : ℂ)) • toMatrix Q +
      (Real.sin θ : ℂ) ^ 2 • toMatrix R := by
  rw [afterTwo, pauli_rotation_branch_anticommute_hermitian hG1 (by decide), partner_one]
  simp only [Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul]
  rw [pauli_rotation_branch_commute hG2 (show sympForm G2 P = 0 by decide),
    pauli_rotation_branch_anticommute_hermitian hG2 (show sympForm G2 Q = 1 by decide), partner_two]
  simp only [smul_add, smul_smul, pow_two, add_assoc]

/-- Pauli coefficients commute with scalar multiplication. Helper for the coefficient
computations below. -/
theorem coeff_smul_local {n : ℕ} (z : ℂ) (A : Matrix (Bits n) (Bits n) ℂ) (p : PauliIndex n) :
    coeff (z • A) p = z * coeff A p := by
  rw [coeff, coeff, Matrix.mul_smul, Matrix.trace_smul, smul_eq_mul]
  ring

/-- The input `P` has no coefficient on the weight-three class of `R`. -/
theorem coeff_P_R : coeff (toMatrix P) (cls R) = 0 := by
  rw [← herm_P, coeff_toMatrix_herm, ite_eq_right (by decide)]
/-- The intermediate Pauli `Q` has no coefficient on the weight-three class of `R`. -/
theorem coeff_Q_R : coeff (toMatrix Q) (cls R) = 0 := by
  rw [← herm_Q, coeff_toMatrix_herm, ite_eq_right (by decide)]
/-- The coefficient of `R = YYX` on its own class is `-1`; the sign comes from the canonical
Hermitian representative, see `R_phase` (`apd:eq:pauli_rotation_branch`). -/
theorem coeff_R_R : coeff (toMatrix R) (cls R) = -1 := by
  have hm : toMatrix R = (-1 : ℂ) • toMatrix (herm (cls R)) := by
    calc
      toMatrix R = toMatrix (phaseMul 2 (herm (cls R))) := congrArg toMatrix R_phase
      _ = (-1 : ℂ) • toMatrix (herm (cls R)) := by rw [toMatrix_phaseMul, iPow_two]
  rw [hm, coeff_smul_local, coeff_toMatrix_herm, ite_eq_left rfl]
  norm_num

/-- The weight-three coefficient of the block output is `-sin² θ`: it is computed, sign
included, rather than assumed to be a positive amplitude (`apd:rmk:multijump`). -/
theorem coeff_afterTwo_R (θ : ℝ) : coeff (afterTwo θ) (cls R) = -(Real.sin θ : ℂ) ^ 2 := by
  rw [afterTwo_expansion, coeff_add, coeff_add, coeff_smul_local, coeff_smul_local,
    coeff_smul_local, coeff_P_R, coeff_Q_R, coeff_R_R]
  ring

/-- For `0 < θ < π` the two-layer output has strictly positive mass above the cutoff two
(`apd:thm:one_step_truncation_error`). -/
theorem highNorm_afterTwo_pos {θ : ℝ} (hθ : 0 < θ) (hθpi : θ < Real.pi) :
    0 < highNorm 2 (afterTwo θ) := by
  apply highNorm_pos_of_coeff_ne_zero (p := cls R) (by decide)
  rw [coeff_afterTwo_R]
  have hs : (Real.sin θ : ℂ) ≠ 0 := by
    exact_mod_cast (ne_of_gt (Real.sin_pos_of_pos_of_lt_pi hθ hθpi))
  exact neg_ne_zero.mpr (pow_ne_zero 2 hs)

/-- A nonzero angle meeting the smallness hypothesis `a ≤ αt/r` of
`pauliNorm_layerStep_error_le_model_of_source_regime` at `α = 1`, `t = 1/50`, `r = 20`
(`apd:thm:one_step_truncation_error`). -/
noncomputable def small : ℝ := 1 / 1000
/-- The generator of layer `T`: `G1` for even `T` and `G2` for odd `T`. -/
def generator (T : ℕ) : PauliString 3 := if T % 2 = 0 then G1 else G2
/-- Singleton layers: each consists of one two-local rotation, so the disjoint-support
condition holds trivially within a layer. -/
noncomputable def layers (T : ℕ) : List (PauliString 3 × ℝ) := [(generator T, small)]

/-- The three-qubit test layers satisfy `IsLayer 2` (`apd:thm:layer_inflow`). -/
theorem layers_isLayer (T : ℕ) : IsLayer 2 ((layers T).map Prod.fst) := by
  constructor
  · simp [layers]
  · intro H hH
    have hH' : H = generator T := by simpa [layers] using hH
    subst H
    unfold generator
    split <;> decide

/-- Every generator of the three-qubit test layers is Hermitian (`apd:thm:layer_inflow`). -/
theorem layers_hermitian (T : ℕ) : ∀ g ∈ layers T, IsSelfAdjoint g.1 := by
  intro g hg
  have hg' : g = (generator T, small) := by simpa [layers] using hg
  subst g
  change IsSelfAdjoint (generator T)
  unfold generator
  split
  · exact hG1
  · exact hG2

/-- The angles obey the absolute-sine bound `|sin θ| ≤ small` (`apd:thm:layer_inflow`). -/
theorem layers_sine_bound (T : ℕ) : ∀ g ∈ layers T, |Real.sin g.2| ≤ small := by
  intro g hg
  have hg' : g = (generator T, small) := by simpa [layers] using hg
  subst g
  simpa [small] using (Real.abs_sin_le_abs (x := small))

/-- The input is `k_o = 1` local on `n = 3` qubits, so `k_o < n`
(`apd:thm:one_step_truncation_error`). -/
theorem input_local (p : PauliIndex 3) (hp : 1 < wt p) : coeff (toMatrix P) p = 0 := by
  rw [← herm_P]
  exact coeff_toMatrix_herm_eq_zero (by simpa [weights.2.2.1] using hp)

/-- The library's block trajectory `layerBlockTraj` coincides with the explicitly written
two-conjugation operator `afterTwo` (`apd:eq:step_component`). -/
theorem block_two_eq : layerBlockTraj layers (toMatrix P) 2 = afterTwo small := by
  simp [layerBlockTraj, layerConj, layers, generator, afterTwo]

/-- **Nonzero discard at `m* = 1`:** with cutoff two on `n = 3` qubits, the first discarded
operator has strictly positive norm, carried by the weight-three Pauli `R`
(`apd:thm:one_step_truncation_error`). -/
theorem first_discard_pos : 0 < pauliNorm (discardedLayerStep layers 2 2 (toMatrix P) 0) := by
  rw [pauliNorm_discardedLayerStep, layerStepTraj_zero, block_two_eq]
  apply highNorm_afterTwo_pos
  · norm_num [small]
  · have h := Real.two_le_pi; norm_num [small]; linarith

/-- The step-count condition `r ≥ 8e²(k_o + k_h − 1)αt` holds at `α = 1`, `t = 1/50`, `r = 20`
with `k_o = 1`, `k_h = 2` (`apd:eq:multijump_factor`). -/
theorem source_step_count : 8 * (Real.exp 1) ^ 2 * ((1 : ℝ) + 2 - 1) * 1 * (1 / 50) ≤ 20 := by
  have hpow := pow_le_pow_left₀ (Real.exp_pos 1).le Real.exp_one_lt_three.le 2
  norm_num at hpow ⊢
  nlinarith

/-- **The error bound in the paper's parameter regime applies where truncation genuinely loses
mass.** Every hypothesis of `pauliNorm_layerStep_error_le_model_of_source_regime` (layer
structure, sine bound, step count, admissibility, `1 ≤ m*`, `5 ≤ r`, input locality) is proved
for the test data; no bound on `β`, on `B = 4eβ`, or on the per-step sum is assumed
(`apd:thm:one_step_truncation_error`/`apd:eq:time_condition`). -/
theorem model_bound_instance :
    pauliNorm (((layerBlockEnd layers 2) ^ 20) (toMatrix P) -
        layerStepTraj layers 2 2 (toMatrix P) 20) ≤
      decayBase 2 2 1 (1 / 50) ^ 2 * (Real.exp 1 * 2) * pauliNorm (toMatrix P) := by
  convert pauliNorm_layerStep_error_le_model_of_source_regime layers 2 (toMatrix P)
    (ko := 1) (kh := 2) (m := 1) (r := 20) (a := small) (α := 1) (t := 1 / 50)
    (by decide) (by decide) layers_isLayer layers_hermitian (by norm_num [small]) layers_sine_bound
    (by norm_num) (by norm_num) (by norm_num [small]) (by simpa using source_step_count)
    (by norm_num [Admissible]) (by decide) (by decide) input_local using 1 <;> norm_num [rungWeight]

/-- The sum of discarded norms over the `r = 20` steps is strictly positive, so the summed bound
`apd:eq:total_high_weight_norm` is exercised on a nonzero left-hand side rather than on an empty
high-weight sector. -/
theorem model_discard_sum_pos :
    0 < ∑ d ∈ Finset.range 20, pauliNorm (discardedLayerStep layers 2 2 (toMatrix P) d) := by
  exact first_discard_pos.trans_le
    (Finset.single_le_sum (fun d _ => pauliNorm_nonneg _) (by simp : 0 ∈ Finset.range 20))

/-- The same data satisfy `t < tZeroModel`: the decay base is below one, so the instance lies
in the short-time regime of `apd:eq:time_condition`, where the right-hand side of
`model_bound_instance` is a genuine decay factor. -/
theorem inside_model_threshold : decayBase 2 2 1 (1 / 50) < 1 := by
  apply decayBase_lt_one (by norm_num) (by norm_num) (by norm_num)
  norm_num [tZeroModel]

#print axioms afterTwo_expansion
#print axioms coeff_afterTwo_R
#print axioms first_discard_pos
#print axioms model_bound_instance
#print axioms model_discard_sum_pos
#print axioms inside_model_threshold

end Lean4LPD.LayerErrorThreeQubitRegression
