/-
Copyright (c) 2026 Jue Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jue Xu
-/
import Lean4LPD.Pauli.LayerLadder
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds

namespace Lean4LPD.MultiJumpWitness
open PauliString Finset

/-!
# A layer witness that populates the multi-jump sector

On a **singleton** layer the pairwise-disjointness clause of `IsLayer` is vacuous and one
rotation climbs at most one rung, so the exactly-`j`-jump components `A^{(j)}` vanish for
`j ≥ 2` (`layerJump_eq_zero_of_length_lt`). The multi-jump sector of `apd:rmk:multijump`, which
is what distinguishes `MultiLadder` from `Ladder`, is then empty. This file gives a
`MultiLadder` instance on which it is not: `G₁ = X₀X₁` and `G₂ = X₂X₃` are disjointly supported
and both anticommute with `s = Z₀Z₂`, so a single layer produces a genuine **double** jump.

## Main results

* `expand`: the two-rotation layer maps `s` to a combination of four Paulis; the `sin² a` term
  sits on the weight-four Pauli `Q₁₂`.
* `physical`: the `MultiLadder` obtained from `pauliMultiLadder` over the two-element layer.
* `physical_N_two_pos`: its mass strictly above rung two is positive after a single layer.
-/

/-- The first generator `X₀X₁`. -/
def G₁ : PauliString 4 := ⟨![1, 1, 0, 0], 0, 0⟩
/-- The second generator `X₂X₃`, supported disjointly from `G₁`. -/
def G₂ : PauliString 4 := ⟨![0, 0, 1, 1], 0, 0⟩
/-- The weight-two input `Z₀Z₂`, which anticommutes with both generators. -/
def s  : PauliString 4 := ⟨0, ![1, 0, 1, 0], 0⟩

/-- The sine partner of `s` under the rotation generated by `G₂` (a single jump). -/
def Q₂  : PauliString 4 := phaseMul 1 (G₂ * s)
/-- The sine partner of `s` under the rotation generated by `G₁` (a single jump). -/
def Q₁  : PauliString 4 := phaseMul 1 (G₁ * s)
/-- The sine partner of `Q₂` under the rotation generated by `G₁`: the double-jump Pauli, of
weight four. -/
def Q₁₂ : PauliString 4 := phaseMul 1 (G₁ * Q₂)
/-- The class (Pauli index) of the double-jump Pauli `Q₁₂`. -/
def c₁₂ : PauliIndex 4 := cls Q₁₂

theorem sa_G₁ : IsSelfAdjoint G₁ := isSelfAdjoint_iff_phase.2 (by decide)
theorem sa_G₂ : IsSelfAdjoint G₂ := isSelfAdjoint_iff_phase.2 (by decide)
theorem sf₂s  : sympForm G₂ s = 1 := by decide
theorem sf₁s  : sympForm G₁ s = 1 := by decide
theorem sf₁Q₂ : sympForm G₁ Q₂ = 1 := by decide

theorem weight_s  : weight s = 2 := by decide
theorem herm_s    : herm (cls s) = s := by decide
theorem wt_c₁₂    : wt c₁₂ = 4 := by decide
theorem Q₁₂_eq    : Q₁₂ = phaseMul 2 (herm c₁₂) := by decide
theorem ne_s'     : c₁₂ ≠ cls s  := by decide
theorem ne_Q₁'    : c₁₂ ≠ cls Q₁ := by decide
theorem ne_Q₂'    : c₁₂ ≠ cls Q₂ := by decide
theorem rungW223  : rungWeight 2 2 2 = 3 := by decide

/-- The nonzero small angle `1/100` of both rotations. -/
noncomputable def a : ℝ := 1 / 100
/-- Every layer consists of the two disjointly supported rotations generated by `G₁` and `G₂`. -/
noncomputable def lay : ℕ → List (PauliString 4 × ℝ) := fun _ => [(G₁, a), (G₂, a)]
/-- No truncation: every Pauli index is retained after every layer. -/
def keep : ℕ → Finset (PauliIndex 4) := fun _ => univ

theorem sin_a_pos : 0 < Real.sin a := by
  apply Real.sin_pos_of_pos_of_lt_pi
  · norm_num [a]
  · have hp := Real.two_le_pi
    norm_num [a]
    linarith

/-! ### The operator expansion -/

theorem inner₂ : layerConj [(G₂, a)] (toMatrix s)
    = (Real.cos a : ℂ) • toMatrix s + (Real.sin a : ℂ) • toMatrix Q₂ := by
  change rot (toMatrix G₂) a * layerConj [] (toMatrix s) * rot (toMatrix G₂) (-a) = _
  change rot (toMatrix G₂) a * toMatrix s * rot (toMatrix G₂) (-a) = _
  rw [pauli_rotation_branch_anticommute_hermitian sa_G₂ sf₂s]
  rfl

/-- Each branch produced by the rotation generated by `G₂` branches again under the rotation
generated by `G₁`. The `sin² a` term, on `Q₁₂`, is the double jump. -/
theorem expand : layerConj (lay 0) (toMatrix s)
    = (Real.cos a : ℂ) • ((Real.cos a : ℂ) • toMatrix s + (Real.sin a : ℂ) • toMatrix Q₁)
      + (Real.sin a : ℂ) • ((Real.cos a : ℂ) • toMatrix Q₂
          + (Real.sin a : ℂ) • toMatrix Q₁₂) := by
  change rot (toMatrix G₁) a * layerConj [(G₂, a)] (toMatrix s) * rot (toMatrix G₁) (-a) = _
  rw [inner₂, Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul,
    Matrix.mul_smul, Matrix.smul_mul,
    pauli_rotation_branch_anticommute_hermitian sa_G₁ sf₁s,
    pauli_rotation_branch_anticommute_hermitian sa_G₁ sf₁Q₂]
  rfl

/-! ### The double-jump coefficient -/

theorem coeff_smul {n : ℕ} (c : ℂ) (M : Matrix (Bits n) (Bits n) ℂ) (p : PauliIndex n) :
    coeff (c • M) p = c * coeff M p := by
  simp only [coeff, Matrix.mul_smul, Matrix.trace_smul, smul_eq_mul]; ring

theorem coeff_add {n : ℕ} (A B : Matrix (Bits n) (Bits n) ℂ) (p : PauliIndex n) :
    coeff (A + B) p = coeff A p + coeff B p := by
  simp only [coeff, Matrix.mul_add, Matrix.trace_add]; ring

/-- A Pauli operator's coefficient vanishes off its own class. -/
theorem coeff_eq_zero_of_ne {n : ℕ} (t : PauliString n) (p : PauliIndex n) (h : p ≠ cls t) :
    coeff (toMatrix t) p = 0 := by
  rw [coeff, ← star_toMatrix_of_isSelfAdjoint (isSelfAdjoint_herm p),
    trace_star_toMatrix_mul_eq_zero, mul_zero]
  rintro ⟨hx, hz⟩
  exact h (Prod.ext hx hz)

theorem coeff_Q₁₂ : coeff (toMatrix Q₁₂) c₁₂ = -1 := by
  rw [Q₁₂_eq, toMatrix_phaseMul, iPow_two, coeff_smul, coeff_toMatrix_herm, ite_eq_left rfl]
  ring

theorem coeff_expand : coeff (layerConj (lay 0) (toMatrix s)) c₁₂
    = -((Real.sin a : ℂ) * (Real.sin a : ℂ)) := by
  rw [expand, coeff_add, coeff_smul, coeff_smul, coeff_add, coeff_add,
    coeff_smul, coeff_smul, coeff_smul, coeff_smul,
    coeff_eq_zero_of_ne _ _ ne_s', coeff_eq_zero_of_ne _ _ ne_Q₁',
    coeff_eq_zero_of_ne _ _ ne_Q₂', coeff_Q₁₂]
  ring

/-! ### The `MultiLadder` instance over a genuine two-element layer -/

theorem lay_isLayer (T : ℕ) : IsLayer 2 ((lay T).map Prod.fst) := by
  constructor
  · change [G₁, G₂].Pairwise _; decide
  · intro G hG
    change G ∈ [G₁, G₂] at hG
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hG
    rcases hG with rfl | rfl <;> decide

theorem lay_herm (T : ℕ) : ∀ g ∈ lay T, IsSelfAdjoint g.1 := by
  intro g hg
  simp only [lay, List.mem_cons, List.not_mem_nil, or_false] at hg
  rcases hg with rfl | rfl
  · exact sa_G₁
  · exact sa_G₂

theorem lay_sine (T : ℕ) : ∀ g ∈ lay T, |Real.sin g.2| ≤ a := by
  intro g hg
  simp only [lay, List.mem_cons, List.not_mem_nil, or_false] at hg
  rcases hg with rfl | rfl <;> simpa [a] using (Real.abs_sin_le_abs (x := a))

theorem input_local (p : PauliIndex 4) (hp : 2 < wt p) : coeff (toMatrix s) p = 0 := by
  rw [← herm_s]
  exact coeff_toMatrix_herm_eq_zero (by simpa [wt, weight_s, herm_s] using hp)

theorem beta_lt_one : betaOf 1 2 a < 1 := by
  unfold betaOf rungW a
  norm_num
  nlinarith [Real.exp_one_lt_three]

/-- The `MultiLadder` obtained from `pauliMultiLadder` over a genuine **two-element**
disjoint-support layer, with `k_o = 2` and `k_h = 2`. -/
noncomputable def physical :=
  pauliMultiLadder lay keep (toMatrix s) (ko := 2) (kh := 2) (by decide)
    lay_isLayer lay_herm (by norm_num [a]) lay_sine
    (by simpa using beta_lt_one) input_local

theorem traj_one : layerTraj lay keep (toMatrix s) 1 = layerConj (lay 0) (toMatrix s) := by
  rw [layerTraj_succ, layerTraj_zero]
  exact truncOp_univ _

/-- **Mass strictly above rung two after a single layer.**

With `k_o = 2` and `k_h = 2`, rung two is weight three and the input `s` has weight two. On a
singleton layer one rotation climbs at most one rung, so `A^{(j)} = 0` for `j ≥ 2` and no mass
lies above rung two after one layer. Here the two disjoint rotations of the layer act jointly:
the weight-four Pauli `Q₁₂`, proportional to `G₁G₂s`, carries the coefficient `-sin² a`
(`coeff_expand`). This populates the multi-jump sector of `apd:rmk:multijump`, the part of
`MultiLadder` that `Ladder` does not have. -/
theorem physical_N_two_pos : 0 < physical.N 2 1 := by
  have hN : physical.N 2 1 = highNorm 3 (layerConj (lay 0) (toMatrix s)) := by
    show highNorm (rungWeight 2 2 2) (layerTraj lay keep (toMatrix s) 1) = _
    rw [rungW223, traj_one]
  rw [hN]
  refine highNorm_pos_of_coeff_ne_zero (p := c₁₂) (by rw [wt_c₁₂]; omega) ?_
  rw [coeff_expand]
  simp only [ne_eq, neg_eq_zero, ← Complex.ofReal_mul, Complex.ofReal_eq_zero,
    mul_self_eq_zero]
  exact ne_of_gt sin_a_pos

#print axioms physical_N_two_pos

end Lean4LPD.MultiJumpWitness
