import Lean4LPD.Pauli.TruncationError
import Lean4LPD.Pauli.DiscardWitness

/-!
# Regression tests for the operator telescope of the truncation error

These tests exercise `Lean4LPD.Pauli.TruncationError`: the operator telescope of
`apd:thm:triangle` for the evolution truncated at the end of every step, with the discarded
operators of `apd:eq:step_component`, and its norm-level consequence. Besides the boundary cases
of zero steps and of an empty block, they use the two-qubit witness of
`Lean4LPD.Pauli.DiscardWitness`, on which the first discarded operator has norm one while the
retained operator has zero high-weight mass.

## Main results

* `one_step_error_norm`, `one_step_discard_sum`: after one step the error norm and the sum of
  discarded norms both equal one, so the norm-level bound is attained.
* `retained_mass_cannot_bound_error`: the high-weight mass of the retained operator does not
  bound the error; it is `0` while the error norm is `1`.
* `two_step_error`, `unpropagated_discard_sum_fails`: after two steps the error is `G`, whereas
  the plain sum of the discarded operators is `Q`. Each discarded operator has to be evolved
  through its remaining blocks, as in the telescope.

The tests concern the normalized Pauli norm only; they make no statement about expectation
values.
-/

namespace Lean4LPD.TruncationErrorRegression

open Finset PauliString

example {n : ℕ} (Gs : ℕ → PauliString n) (θ : ℕ → ℝ)
    (period wstar : ℕ) (O : Matrix (Bits n) (Bits n) ℂ) :
    ((blockEnd Gs θ period) ^ 0) O - trotterStepTraj Gs θ period wstar O 0 = 0 := by
  simp

example {n : ℕ} (Gs : ℕ → PauliString n) (θ : ℕ → ℝ)
    (O : Matrix (Bits n) (Bits n) ℂ) (r : ℕ) :
    ((blockEnd Gs θ 0) ^ r) O = O := by
  rw [blockEnd_pow_eq_periodic_traj]
  simp

example {n : ℕ} (Gs : ℕ → PauliString n) (θ : ℕ → ℝ)
    (period wstar : ℕ) (O : Matrix (Bits n) (Bits n) ℂ) :
    ((blockEnd Gs θ period) ^ 1) O - trotterStepTraj Gs θ period wstar O 1 =
      discardedStep Gs θ period wstar O 0 := by
  simpa using trotterStep_telescoping Gs θ period wstar O 1

example {n : ℕ} (Gs : ℕ → PauliString n) (θ : ℕ → ℝ)
    (period wstar : ℕ) (O : Matrix (Bits n) (Bits n) ℂ) :
    ((blockEnd Gs θ period) ^ 2) O - trotterStepTraj Gs θ period wstar O 2 =
      blockEnd Gs θ period (discardedStep Gs θ period wstar O 0) +
        discardedStep Gs θ period wstar O 1 := by
  simpa [Finset.sum_range_succ] using trotterStep_telescoping Gs θ period wstar O 2

open DiscardWitness

/-- After one step the error norm is exactly one: the error is the first discarded operator
`Q`. Together with `one_step_discard_sum` this shows that the norm-level counterpart of
`apd:thm:triangle` is attained on a nonzero example. -/
theorem one_step_error_norm :
    pauliNorm (((blockEnd Gs angles 2) ^ 1) (toMatrix P) -
      trotterStepTraj Gs angles 2 1 (toMatrix P) 1) = 1 := by
  rw [pow_one, blockEnd_apply, traj_two, step_one, sub_zero, Q_pauliNorm]

/-- On the witness, the right-hand side of the norm-level triangle bound of `apd:thm:triangle`
is one, not zero. -/
theorem one_step_discard_sum :
    (∑ d ∈ range 1, pauliNorm (discardedStep Gs angles 2 1 (toMatrix P) d)) = 1 := by
  simp [discardedStep_pauliNorm]

example :
    pauliNorm (((blockEnd Gs angles 2) ^ 1) (toMatrix P) -
        trotterStepTraj Gs angles 2 1 (toMatrix P) 1) =
      ∑ d ∈ range 1, pauliNorm (discardedStep Gs angles 2 1 (toMatrix P) d) := by
  rw [one_step_error_norm, one_step_discard_sum]

/-- The discarded (pre-cut) mass in `apd:thm:triangle` cannot be replaced by the retained
(post-cut) high-weight mass: on the witness the error norm is `1` while the retained high-weight
mass is `0`. -/
theorem retained_mass_cannot_bound_error :
    ¬ pauliNorm (((blockEnd Gs angles 2) ^ 1) (toMatrix P) -
        trotterStepTraj Gs angles 2 1 (toMatrix P) 1) ≤
      highNorm 1 (trotterStepTraj Gs angles 2 1 (toMatrix P) 1) := by
  rw [one_step_error_norm, highNorm_trotterStepTraj_succ Gs angles 2 1 (toMatrix P) 0]
  norm_num

/-- Conjugating `Q` by the rotation generated by `G` through `π / 2` gives `-P`. Helper for the
second block in `residual_block_Q`. -/
theorem rotate_Q_to_neg_P :
    rot (toMatrix G) (Real.pi / 2) * toMatrix Q * rot (toMatrix G) (-(Real.pi / 2)) =
      -toMatrix P := by
  have ha : sympForm G Q = 1 := by decide
  have hp : phaseMul 1 (G * Q) = phaseMul 2 P := by decide
  rw [pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_G ha,
    Real.cos_pi_div_two, Real.sin_pi_div_two, hp]
  simp

/-- Conjugating `P` by the rotation generated by `Q` through `π / 2` gives `-G`. Helper for the
second block in `residual_block_Q`. -/
theorem rotate_P_to_neg_G :
    rot (toMatrix Q) (Real.pi / 2) * toMatrix P * rot (toMatrix Q) (-(Real.pi / 2)) =
      -toMatrix G := by
  have ha : sympForm Q P = 1 := by decide
  have hp : phaseMul 1 (Q * P) = phaseMul 2 G := by decide
  rw [pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_Q ha,
    Real.cos_pi_div_two, Real.sin_pi_div_two, hp]
  simp

/-- The first discarded operator `Q` evolves to `G` under its one remaining block. This tests
the exponent of the residual evolution in the telescope of `apd:thm:triangle`. -/
theorem residual_block_Q : traj Gs angles (toMatrix Q) 2 = toMatrix G := by
  have hfirst : traj Gs angles (toMatrix Q) 1 = -toMatrix P := by
    rw [traj_succ, traj_zero]
    simpa [Gs, angles] using rotate_Q_to_neg_P
  rw [traj_succ, hfirst]
  change rot (toMatrix Q) (Real.pi / 2) * (-toMatrix P) *
      rot (toMatrix Q) (-(Real.pi / 2)) = toMatrix G
  rw [Matrix.mul_neg, Matrix.neg_mul, rotate_P_to_neg_G, neg_neg]

/-- On the witness, the retained operator is still zero at the second step boundary
(`apd:eq:step_component`). -/
theorem kept_two : trotterStepTraj Gs angles 2 1 (toMatrix P) 2 = 0 := by
  rw [trotterStepTraj_succ, step_one, traj_zero_input]
  simp [truncOp, coeff]

/-- Nothing further is discarded from a retained operator that is already zero
(`apd:eq:step_component`). -/
theorem discard_one : discardedStep Gs angles 2 1 (toMatrix P) 1 = 0 := by
  rw [discardedStep, step_one, traj_zero_input, kept_two, sub_self]

/-- After two blocks the error is `G`: the first discarded operator `Q` evolved through the
remaining block, as the telescope of `apd:thm:triangle` prescribes. -/
theorem two_step_error :
    ((blockEnd Gs angles 2) ^ 2) (toMatrix P) -
      trotterStepTraj Gs angles 2 1 (toMatrix P) 2 = toMatrix G := by
  rw [pow_succ', pow_one, AddMonoid.End.coe_mul, Function.comp_apply,
    blockEnd_apply, blockEnd_apply, traj_two, residual_block_Q, kept_two, sub_zero]

/-- The residual evolution in the operator identity of `apd:thm:triangle` cannot be omitted: on
the two-qubit witness the two-step error is `G`, whereas the plain sum of the discarded
operators is `Q`. -/
theorem unpropagated_discard_sum_fails :
    ((blockEnd Gs angles 2) ^ 2) (toMatrix P) -
        trotterStepTraj Gs angles 2 1 (toMatrix P) 2 ≠
      ∑ d ∈ range 2, discardedStep Gs angles 2 1 (toMatrix P) d := by
  rw [two_step_error]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
    discardedStep_zero, discard_one, add_zero]
  intro heq
  have : G = Q := toMatrix_injective heq
  exact (by decide : G ≠ Q) this

example :
    pauliNorm (traj (fun g => Gs (g % 2)) (fun g => angles (g % 2)) (toMatrix P) (2 * 2) -
        trotterTraj Gs angles 2 1 (toMatrix P) (2 * 2)) ≤
      ∑ d ∈ range 2, pauliNorm (discardedStep Gs angles 2 1 (toMatrix P) d) :=
  pauliNorm_trotterTraj_error_le generators_selfAdjoint angles 2 1 (toMatrix P) 2 (by decide)

#print axioms trotterStep_telescoping
#print axioms blockEnd_pow_eq_periodic_traj
#print axioms periodic_traj_sub_trotterStepTraj
#print axioms pauliNorm_trotterStep_error_le
#print axioms pauliNorm_trotterTraj_error_le
#print axioms pauliNorm_trotterStep_error_le_highNorm
#print axioms unpropagated_discard_sum_fails
#print axioms retained_mass_cannot_bound_error

end Lean4LPD.TruncationErrorRegression
